# Generated by Django 3.1.2 on 2020-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
